# Generated by Django 6.1.1 on 2026-09-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_taxonomy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
